### ISSUE TITLE
The zip files in google drive are corrupted ?

### ISSUE THREAD

**Issue by jaiabhayk** [anlthms/dsb-2017#1]
Its seems the zip files in the shared google drive are corrupted Or I am missing something ? :-

(.venv2)bash-4.2$ unzip subset0.zip 
Archive:  subset0.zip
warning [subset0.zip]:  2516934707 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [subset0.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)

**Comment by mattmacy** [comment]
@jaiabhayk they're misnamed - you need to do: 7za x subset0.zip

**Comment by anlthms** [comment]
Right, they are compressed with 7z.
