### ISSUE TITLE
how to draw a 3d plot for chunk like yours?

### ISSUE THREAD

**Issue by tangzk** [anlthms/dsb-2017#7]
Hi, anlthms, thank you for your script. I have run your script but got a different result. I think if I can plot the chunk in 3d, the difference may be easily detected. 
Would you mind telling me the script for visualizing? thank you.

**Comment by anlthms** [comment]
I used the plot_3d function from this script: https://www.kaggle.com/gzuidhof/data-science-bowl-2017/full-preprocessing-tutorial
